<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	
</body>
<script>
	try{
		//监听的代码块
		//throw "error curr";
		//var 1a = "111";//不能以数字开头
		//
	}catch(error){
		//捕获到异常后的处理
		console.log(error);
	}finally{
		//无论是否捕获到异常都会执行
	}


	//JS中异步回调函数捕获异常的问题
	//1
	try{//定义和调用都在try里面
		//RangeError：数组对象或参数超出有效范围
	    function abc(x,cb){
		    console.log(x);
            cb();
        }
	    abc("xx",function(){
	        var arr = new Array(-1);
	    });
    }
    catch(e){
	   console.log(e);
    }

    //2
    try{//函数定义在里面
	    function abc(x,cb){
		    console.log(x);
            cb();
        }
    }
    catch(e){
	    console.log(e);
    }
    //代码执行在外面
    abc("xx",function(){//调用在外面 
        var arr = new Array(-1);
    });
</script>
</html>